import type { InventoryItem, StockBatch, StockMovement } from "../../components/inventory";

export const initialInventory: InventoryItem[] = [
  {
    productId: 1,
    productName: "مياه معدنية",
    productCode: "PRD-001",
    categoryName: "مشروبات",
    unit: "قطعة",
    totalQuantity: 68,
    minimumStock: 20,
    batchesCount: 2,
    averagePurchasePrice: 2500,
    stockValue: 170000,
    nearestExpiryDate: "2027-01-15",
    suppliersCount: 2,
    supplierNames: ["شركة النبع", "مؤسسة الصفاء"],
    status: "available",
  },
  {
    productId: 2,
    productName: "عصير برتقال",
    productCode: "PRD-002",
    categoryName: "مشروبات",
    unit: "علبة",
    totalQuantity: 8,
    minimumStock: 10,
    batchesCount: 1,
    averagePurchasePrice: 6000,
    stockValue: 48000,
    nearestExpiryDate: "2026-08-12",
    suppliersCount: 1,
    supplierNames: ["شركة الفجر الغذائية"],
    status: "low",
  },
  {
    productId: 3,
    productName: "سكر أبيض",
    productCode: "PRD-003",
    categoryName: "مواد غذائية",
    unit: "كيس",
    totalQuantity: 0,
    minimumStock: 5,
    batchesCount: 1,
    averagePurchasePrice: 8500,
    stockValue: 0,
    nearestExpiryDate: null,
    suppliersCount: 1,
    supplierNames: ["شركة النور"],
    status: "out",
  },
  {
    productId: 4,
    productName: "مناديل ورقية",
    productCode: "PRD-004",
    categoryName: "منظفات وورقيات",
    unit: "علبة",
    totalQuantity: 22,
    minimumStock: 8,
    batchesCount: 1,
    averagePurchasePrice: 4500,
    stockValue: 99000,
    nearestExpiryDate: null,
    suppliersCount: 1,
    supplierNames: ["مؤسسة الأمانة"],
    status: "available",
  },
  {
    productId: 5,
    productName: "زيت نباتي",
    productCode: "PRD-005",
    categoryName: "مواد غذائية",
    unit: "عبوة",
    totalQuantity: 14,
    minimumStock: 6,
    batchesCount: 1,
    averagePurchasePrice: 42000,
    stockValue: 588000,
    nearestExpiryDate: "2027-03-20",
    suppliersCount: 1,
    supplierNames: ["شركة الزيوت الحديثة"],
    status: "available",
  },
];

export const initialBatches: StockBatch[] = [
  {
    id: 14,
    productId: 1,
    batchCode: "BAT-0014",
    supplierId: 1,
    supplierName: "شركة النبع",
    quantity: 50,
    remainingQuantity: 40,
    purchasePrice: 2400,
    receivedDate: "2026-07-29",
    expiryDate: "2027-01-15",
    notes: null,
  },
  {
    id: 15,
    productId: 1,
    batchCode: "BAT-0015",
    supplierId: 2,
    supplierName: "مؤسسة الصفاء",
    quantity: 28,
    remainingQuantity: 28,
    purchasePrice: 2643,
    receivedDate: "2026-07-20",
    expiryDate: "2027-02-10",
    notes: null,
  },
  {
    id: 8,
    productId: 2,
    batchCode: "BAT-0008",
    supplierId: 3,
    supplierName: "شركة الفجر الغذائية",
    quantity: 10,
    remainingQuantity: 8,
    purchasePrice: 6000,
    receivedDate: "2026-07-15",
    expiryDate: "2026-08-12",
    notes: "دفعة قريبة الانتهاء.",
  },
  {
    id: 5,
    productId: 3,
    batchCode: "BAT-0005",
    supplierId: 4,
    supplierName: "شركة النور",
    quantity: 4,
    remainingQuantity: 0,
    purchasePrice: 8500,
    receivedDate: "2026-07-10",
    expiryDate: null,
    notes: null,
  },
  {
    id: 11,
    productId: 4,
    batchCode: "BAT-0011",
    supplierId: 5,
    supplierName: "مؤسسة الأمانة",
    quantity: 22,
    remainingQuantity: 22,
    purchasePrice: 4500,
    receivedDate: "2026-07-18",
    expiryDate: null,
    notes: null,
  },
  {
    id: 2,
    productId: 5,
    batchCode: "BAT-0002",
    supplierId: 6,
    supplierName: "شركة الزيوت الحديثة",
    quantity: 20,
    remainingQuantity: 14,
    purchasePrice: 42000,
    receivedDate: "2026-07-01",
    expiryDate: "2027-03-20",
    notes: null,
  },
];

export const initialMovements: StockMovement[] = [
  {
    id: 1,
    createdAt: "2026-07-29 10:35",
    productId: 1,
    productName: "مياه معدنية",
    productCode: "PRD-001",
    unit: "قطعة",
    type: "purchase",
    quantity: 50,
    balanceAfter: 78,
    referenceId: 101,
    referenceNumber: "PUR-0101",
    stockBatchId: 14,
    batchCode: "BAT-0014",
    supplierId: 1,
    supplierName: "شركة النبع",
    notes: "استلام دفعة جديدة من المورد.",
  },
  {
    id: 2,
    createdAt: "2026-07-29 11:20",
    productId: 1,
    productName: "مياه معدنية",
    productCode: "PRD-001",
    unit: "قطعة",
    type: "sale",
    quantity: -10,
    balanceAfter: 68,
    referenceId: 214,
    referenceNumber: "SAL-0214",
    stockBatchId: 14,
    batchCode: "BAT-0014",
    supplierId: 1,
    supplierName: "شركة النبع",
    notes: null,
  },
  {
    id: 3,
    createdAt: "2026-07-29 12:05",
    productId: 2,
    productName: "عصير برتقال",
    productCode: "PRD-002",
    unit: "علبة",
    type: "adjustment_out",
    quantity: -2,
    balanceAfter: 8,
    referenceId: 31,
    referenceNumber: "ADJ-0031",
    stockBatchId: 8,
    batchCode: "BAT-0008",
    supplierId: 3,
    supplierName: "شركة الفجر الغذائية",
    notes: "تلف عبوتين أثناء النقل الداخلي.",
  },
  {
    id: 4,
    createdAt: "2026-07-28 16:40",
    productId: 3,
    productName: "سكر أبيض",
    productCode: "PRD-003",
    unit: "كيس",
    type: "purchase_return",
    quantity: -4,
    balanceAfter: 0,
    referenceId: 19,
    referenceNumber: "PRT-0019",
    stockBatchId: 5,
    batchCode: "BAT-0005",
    supplierId: 4,
    supplierName: "شركة النور",
    notes: "إعادة أكياس متضررة إلى المورد.",
  },
  {
    id: 5,
    createdAt: "2026-07-28 14:10",
    productId: 4,
    productName: "مناديل ورقية",
    productCode: "PRD-004",
    unit: "علبة",
    type: "sale_return",
    quantity: 3,
    balanceAfter: 22,
    referenceId: 44,
    referenceNumber: "SRT-0044",
    stockBatchId: 11,
    batchCode: "BAT-0011",
    supplierId: 5,
    supplierName: "مؤسسة الأمانة",
    notes: "مرتجع عميل بحالة قابلة للبيع.",
  },
  {
    id: 6,
    createdAt: "2026-07-27 09:00",
    productId: 5,
    productName: "زيت نباتي",
    productCode: "PRD-005",
    unit: "عبوة",
    type: "opening_balance",
    quantity: 20,
    balanceAfter: 20,
    referenceId: null,
    referenceNumber: null,
    stockBatchId: 2,
    batchCode: "BAT-0002",
    supplierId: 6,
    supplierName: "شركة الزيوت الحديثة",
    notes: "الرصيد الافتتاحي عند بدء استخدام النظام.",
  },
];

