import { useState } from "react";
import { ArrowRight, Save } from "lucide-react";
import { Navigate, useNavigate, useParams } from "react-router-dom";
import { Button, Card, FormField, Input, NumberInput, PageHeader, Textarea } from "../../components/ui";
import { useInventory } from "./InventoryContext";

export default function StockBatchFormPage() {
  const { productId } = useParams(); const navigate = useNavigate(); const { getProduct, saveBatch } = useInventory(); const product = getProduct(Number(productId));
  const [batchCode, setBatchCode] = useState(`BAT-${Date.now().toString().slice(-4)}`); const [supplierName, setSupplierName] = useState(""); const [quantity, setQuantity] = useState("1"); const [purchasePrice, setPurchasePrice] = useState("0"); const [receivedDate, setReceivedDate] = useState(new Date().toISOString().slice(0, 10)); const [expiryDate, setExpiryDate] = useState(""); const [notes, setNotes] = useState(""); const [error, setError] = useState("");
  if (!product) return <Navigate to="/inventory" replace />;
  function submit(event: React.FormEvent) { event.preventDefault(); const q = Number(quantity), price = Number(purchasePrice); if (!batchCode.trim() || !supplierName.trim() || q <= 0 || price < 0 || !receivedDate) return setError("أكمل الحقول المطلوبة وتأكد من القيم."); saveBatch({ productId: product.productId, batchCode: batchCode.trim(), supplierName: supplierName.trim(), quantity: q, purchasePrice: price, receivedDate, expiryDate, notes: notes.trim() }); navigate(`/inventory/${product.productId}`); }
  return <form onSubmit={submit} className="space-y-6">
    <PageHeader title="إضافة دفعة مخزون" description="إدخال دفعة جديدة وربطها بالمادة والمورد وتواريخ الصلاحية." actions={<Button variant="secondary" startIcon={<ArrowRight size={17} />} onClick={() => navigate(-1)}>رجوع</Button>} />
    <Card header="المادة المحددة"><div className="grid gap-4 md:grid-cols-3"><Info label="المادة" value={product.productName} /><Info label="الكود" value={product.productCode} /><Info label="الرصيد الحالي" value={`${product.totalQuantity.toLocaleString()} ${product.unit}`} /></div></Card>
    <Card header="بيانات الدفعة" description="البيانات الأساسية المستخدمة في التتبع والتكلفة."><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3"><FormField label="رقم الدفعة" required><Input dir="ltr" value={batchCode} onChange={(e) => setBatchCode(e.target.value)} /></FormField><FormField label="اسم المورد" required><Input value={supplierName} placeholder="اسم المورد" onChange={(e) => setSupplierName(e.target.value)} /></FormField><FormField label="الكمية" required><NumberInput min={1} value={quantity} suffix={product.unit} onChange={(e) => setQuantity(e.target.value)} /></FormField><FormField label="سعر الشراء" required><NumberInput min={0} value={purchasePrice} suffix="ل.س" onChange={(e) => setPurchasePrice(e.target.value)} /></FormField><FormField label="تاريخ الاستلام" required><Input type="date" dir="ltr" value={receivedDate} onChange={(e) => setReceivedDate(e.target.value)} /></FormField><FormField label="تاريخ الانتهاء"><Input type="date" dir="ltr" value={expiryDate} onChange={(e) => setExpiryDate(e.target.value)} /></FormField><div className="md:col-span-2 xl:col-span-3"><FormField label="ملاحظات"><Textarea rows={5} value={notes} placeholder="ملاحظات خاصة بالدفعة..." onChange={(e) => setNotes(e.target.value)} /></FormField></div>{error && <p className="md:col-span-2 xl:col-span-3 text-sm font-medium text-[var(--danger)]">{error}</p>}</div></Card>
    <Card header="ملخص الدفعة"><div className="grid gap-4 md:grid-cols-3"><Info label="الكمية" value={`${Number(quantity || 0).toLocaleString()} ${product.unit}`} /><Info label="سعر الوحدة" value={`${Number(purchasePrice || 0).toLocaleString()} ل.س`} /><Info label="قيمة الدفعة" value={`${(Number(quantity || 0) * Number(purchasePrice || 0)).toLocaleString()} ل.س`} /></div></Card>
    <div className="sticky bottom-0 z-10 flex justify-end gap-3 border-t border-[var(--border)] bg-[var(--background)] py-4"><Button variant="secondary" onClick={() => navigate(-1)}>إلغاء</Button><Button type="submit" startIcon={<Save size={17} />}>حفظ الدفعة</Button></div>
  </form>;
}
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-[var(--radius-sm)] border border-[var(--border)] bg-[var(--surface-subtle)] p-4"><p className="text-xs text-[var(--text-muted)]">{label}</p><p className="mt-1 font-bold">{value}</p></div>; }
