export const PATHS = {
    LOGIN: "/login",
    DASHBOARD: "/",
    PRODUCTS: "/products",
    PRODUCT_NEW: "/products/new",
    PRODUCT_EDIT: "/products/:productId/edit",

    CUSTOMERS: "/customers",
    CUSTOMER_NEW: "/customers/new",
    CUSTOMER_DETAILS: "/customers/:customerId",
    CUSTOMER_EDIT: "/customers/:customerId/edit",

    INVENTORY: "/inventory",
    INVENTORY_DETAILS: "/inventory/:productId",
    INVENTORY_ADJUST: "/inventory/:productId/adjust",
    INVENTORY_BATCH_NEW: "/inventory/:productId/batches/new",
    INVENTORY_MOVEMENT_DETAILS: "/inventory/:productId/movements/:movementId",

    SUPPLIERS: "/suppliers",
    SUPPLIER_NEW: "/suppliers/new",
    SUPPLIER_DETAILS: "/suppliers/:supplierId",
    SUPPLIER_EDIT: "/suppliers/:supplierId/edit",
    PURCHASES: "/purchases",
    PURCHASE_NEW: "/purchases/new",
    PURCHASE_DETAILS: "/purchases/:purchaseId",
    PURCHASE_EDIT: "/purchases/:purchaseId/edit",
    PURCHASE_PAYMENT_NEW: "/purchases/:purchaseId/payments/new",
    PURCHASE_PRINT: "/purchases/:purchaseId/print",
    SALES: "/sales",
    SALE_NEW: "/sales/new",
    SALE_DETAILS: "/sales/:saleId",
    SALE_EDIT: "/sales/:saleId/edit",
    SALE_PAYMENT_NEW: "/sales/:saleId/payments/new",
    SALE_PRINT: "/sales/:saleId/print",
    CASHBOXES: "/cashboxes",
    CASHBOX_NEW: "/cashboxes/new",
    CASHBOX_DETAILS: "/cashboxes/:id",
    CASHBOX_EDIT: "/cashboxes/:id/edit",
    CASHBOX_TRANSACTION_NEW: "/cashboxes/:cashboxId/transactions/new",
    CASHBOX_MOVEMENTS: "/cashboxes/:id/movements",
    CASHBOX_TRANSFER_NEW: "/cashboxes/transfers/new",
    TRANSACTIONS: "/transactions",
    TRANSACTION_NEW: "/transactions/new",
    TRANSACTION_DETAILS: "/transactions/:id",
    TRANSACTION_EDIT: "/transactions/:id/edit",
    TRANSACTION_CATEGORIES: "/transaction-categories",
    TRANSACTION_CATEGORY_NEW: "/transaction-categories/new",
    TRANSACTION_CATEGORY_EDIT: "/transaction-categories/:id/edit",
    USERS: "/users",
    REPORTS: "/reports",
    SETTINGS: "/settings",
    SETTINGS_COMPANY: "/settings/company",
    SETTINGS_BACKUP: "/settings/backup",
    SETTINGS_ABOUT: "/settings/about",
    SETTINGS_APPEARANCE: "/settings/appearance",
} as const;