import { useEffect, useMemo, useState } from "react";
import { FileDown, Printer } from "lucide-react";
import { useParams } from "react-router-dom";
import { BackButton, Button, EmptyState, PageHeader } from "../../components/ui";
import { defaultCompanySettings, settingsService, type CompanySettings } from "../settings/settingsService";

type Kind = "payment"|"transaction"|"transfer"|"customer"|"supplier"|"cashbox"|"consignment";
const n=(v:unknown)=>Number(v??0); const fmt=(v:unknown)=>n(v).toLocaleString("en-US",{maximumFractionDigits:2});
const date=(v:unknown)=>String(v??"").replace("T"," ").slice(0,19);
const money=(v:unknown,c="SYP")=>`${fmt(v)} ${c==="SYP"?"ل.س":c}`;

export default function DocumentPrintPage({kind}:{kind:Kind}){
 const params=useParams(); const raw=params.id||params.customerId||params.supplierId||params.purchaseId||params.groupId||"";
 const id=kind==="transfer"?raw:Number(raw); const [data,setData]=useState<any>(); const [company,setCompany]=useState<CompanySettings>(defaultCompanySettings); const [error,setError]=useState(""); const [savingPdf,setSavingPdf]=useState(false);
 useEffect(()=>{let off=false;(async()=>{try{
  const api=window.stockliteApi.printDocuments;
  const loaders: Record<Kind, (documentId: number|string)=>Promise<unknown>> = {
    payment: (documentId) => api.payment(Number(documentId)),
    transaction: (documentId) => api.transaction(Number(documentId)),
    transfer: (documentId) => api.transfer(String(documentId)),
    customer: (documentId) => api.customerStatement(Number(documentId)),
    supplier: (documentId) => api.supplierStatement(Number(documentId)),
    cashbox: (documentId) => api.cashboxStatement(Number(documentId)),
    consignment: (documentId) => api.consignment(Number(documentId)),
  };
  const loader=loaders[kind];
  if(!loader) throw new Error("نوع مستند الطباعة غير مدعوم");
  const [d,c]=await Promise.all([loader(id),settingsService.loadCompany()]);
  if(!off){setData(d);setCompany(c)}
 }catch(e:unknown){if(!off)setError(e instanceof Error?e.message:"تعذر تجهيز المستند")}})();return()=>{off=true}},[kind,id]);
 const title=useMemo(()=>({payment:"سند مالي",transaction:"مستند معاملة مالية",transfer:"سند تحويل بين الصناديق",customer:"كشف حساب عميل",supplier:"كشف حساب مورد",cashbox:"كشف حركة صندوق",consignment:"تسوية أمانة"}[kind]),[kind]);
 if(error)return <EmptyState title="تعذر تجهيز المستند" description={error}/>; if(!data)return <div className="p-12 text-center">جاري تجهيز الطباعة...</div>;
 const print=()=>window.print();
 const savePdf=async()=>{try{setSavingPdf(true);await window.stockliteApi.system.saveCurrentPageAsPdf({fileName:`${title} ${raw}`})}catch(e:unknown){setError(e instanceof Error?e.message:"تعذر حفظ ملف PDF")}finally{setSavingPdf(false)}};
 return <div className="space-y-5"><div className="no-print"><PageHeader title={title} description="مستند موحّد A4 وRTL من البيانات الفعلية للنظام." actions={<div className="flex gap-2"><BackButton/><Button variant="secondary" startIcon={<Printer size={17}/>} onClick={print}>طباعة</Button><Button startIcon={<FileDown size={17}/>} disabled={savingPdf} onClick={()=>void savePdf()}>{savingPdf?"جاري الحفظ...":"حفظ PDF"}</Button></div>}/></div>
 <article className="invoice-print-sheet" dir="rtl"><header className="invoice-print-header"><div className="invoice-company-block"><div className="invoice-company-identity">{company.logo&&<img src={company.logo} className="invoice-logo"/>}<div><h1>{company.name||"اسم الشركة"}</h1><p className="invoice-company-subtitle">{company.address||"نظام المبيعات والمخزون"}</p></div></div><div className="invoice-company-contact">{company.phone&&<p>الهاتف: <bdi>{company.phone}</bdi></p>}{company.email&&<p>البريد: <bdi>{company.email}</bdi></p>}</div></div><div className="invoice-title-box"><span className="invoice-document-label">مستند رسمي</span><h2>{title}</h2><p>تاريخ الطباعة: <bdi>{new Date().toLocaleString("en-GB")}</bdi></p></div></header>
 {kind==="payment"&&<Payment d={data}/>} {kind==="transaction"&&<Transaction d={data}/>} {kind==="transfer"&&<Transfer d={data}/>} {(kind==="customer"||kind==="supplier")&&<Statement d={data}/>} {kind==="cashbox"&&<Cashbox d={data}/>} {kind==="consignment"&&<Consignment d={data}/>} 
 <footer className="invoice-print-footer"><div className="invoice-signatures"><div><span>توقيع المستلم</span><i/></div><div><span>المحاسب</span><i/></div><div><span>الختم والتوقيع</span><i/></div></div><p>{company.invoiceFooter||"تم إنشاء هذا المستند إلكترونيًا."}</p></footer></article></div>
}
const Meta=({items}:{items:[string,unknown][]})=><section className="invoice-meta">{items.map(([k,v])=><div key={k}><span>{k}</span><strong><bdi>{String(v??"—")}</bdi></strong></div>)}</section>;
function Payment({d}:{d:any}){const c=d.currency||"SYP";return <><Meta items={[["رقم السند",d.id],["نوع السند",d.payment_type==="sale"?"سند قبض":"سند دفع"],["الطرف",d.party_name||"بيع نقدي"],["رقم الفاتورة",d.invoice_number],["الصندوق",d.cashbox_name],["التاريخ",date(d.payment_date)]]}/><section className="invoice-summary mt-6"><div className="invoice-total"><span>المبلغ الأصلي</span><strong>{money(d.amount,c)}</strong></div>{c!=="SYP"&&<><div><span>سعر الصرف</span><strong>1 {c} = {fmt(d.exchange_rate)} SYP</strong></div><div><span>القيمة الأساسية</span><strong>{money(d.amount_base,"SYP")}</strong></div></>}<div><span>الحالة</span><strong>{d.status||"active"}</strong></div></section><p className="mt-8">البيان: {d.notes||d.reference_number||"دفعة مرتبطة بفاتورة"}</p></>}
function Transaction({d}:{d:any}){const c=d.cashbox_currency||"SYP";return <><Meta items={[["رقم المستند",d.id],["النوع",d.type==="income"?"إيراد":"مصروف"],["التصنيف",d.category_name],["الصندوق",d.cashbox_name],["التاريخ",date(d.transaction_date)],["المرجع",d.reference_number]]}/><section className="invoice-summary mt-6"><div className="invoice-total"><span>المبلغ</span><strong>{money(d.amount,c)}</strong></div><div><span>الحالة</span><strong>{d.status}</strong></div></section><p className="mt-8">الوصف: {d.description||d.notes||"—"}</p></>}
function Transfer({d}:{d:any}){const out=d.movements.find((x:any)=>x.direction==="out"), inn=d.movements.find((x:any)=>x.direction==="in"),c=out?.cashbox_currency||"SYP";return <><Meta items={[["رقم التحويل",d.transfer_group_id],["من صندوق",out?.cashbox_name],["إلى صندوق",inn?.cashbox_name],["التاريخ",date(out?.transaction_date)],["العملة",c]]}/><section className="invoice-summary mt-6"><div className="invoice-total"><span>قيمة التحويل</span><strong>{money(out?.amount,c)}</strong></div><div><span>رصيد المصدر قبل/بعد</span><strong>{fmt(out?.balance_before)} / {fmt(out?.balance_after)}</strong></div><div><span>رصيد الوجهة قبل/بعد</span><strong>{fmt(inn?.balance_before)} / {fmt(inn?.balance_after)}</strong></div></section></>}
function Statement({d}:{d:any}){return <><Meta items={[["الاسم",d.party.name],["الهاتف",d.party.phone],["العنوان",d.party.address],["الرصيد الحالي",money(d.balance,"SYP")]]}/><h3 className="mt-7 mb-3 font-bold">الفواتير</h3><table className="invoice-items"><thead><tr><th>الرقم</th><th>التاريخ</th><th>الإجمالي</th><th>المدفوع</th><th>المتبقي</th><th>الحالة</th></tr></thead><tbody>{d.invoices.map((x:any)=><tr key={x.id}><td>{x.invoice_number}</td><td>{date(x.invoice_date)}</td><td>{money(x.total,x.currency)}</td><td>{money(x.paid_amount,x.currency)}</td><td>{money(x.remaining_amount,x.currency)}</td><td>{x.status}</td></tr>)}</tbody></table><h3 className="mt-7 mb-3 font-bold">الدفعات</h3><table className="invoice-items"><thead><tr><th>الرقم</th><th>التاريخ</th><th>الصندوق</th><th>المبلغ</th><th>الحالة</th></tr></thead><tbody>{d.payments.map((x:any)=><tr key={x.id}><td>{x.id}</td><td>{date(x.payment_date)}</td><td>{x.cashbox_name}</td><td>{money(x.amount,x.currency)}</td><td>{x.status}</td></tr>)}</tbody></table></>}
function Cashbox({d}:{d:any}){const c=d.cashbox.currency||"SYP";return <><Meta items={[["الصندوق",d.cashbox.name],["العملة",c],["الرصيد الحالي",money(d.cashbox.balance,c)],["عدد الحركات",d.movements.length]]}/><table className="invoice-items mt-7"><thead><tr><th>التاريخ</th><th>النوع</th><th>الاتجاه</th><th>المبلغ</th><th>قبل</th><th>بعد</th></tr></thead><tbody>{d.movements.map((x:any)=><tr key={x.id}><td>{date(x.transaction_date)}</td><td>{x.reference_type}</td><td>{x.direction}</td><td>{money(x.amount,c)}</td><td>{fmt(x.balance_before)}</td><td>{fmt(x.balance_after)}</td></tr>)}</tbody></table></>}
function Consignment({d}:{d:any}){const s=d.settlement,c=s.currency||"SYP";return <><Meta items={[["رقم التسوية",s.id],["الفاتورة",s.invoice_number],["المورد",s.supplier_name],["الصندوق",s.cashbox_name],["التاريخ",date(s.settlement_date)],["الحالة",s.status]]}/><table className="invoice-items mt-7"><thead><tr><th>المنتج</th><th>المباع</th><th>المتبقي</th><th>قيمة المبيعات</th><th>السياسة</th></tr></thead><tbody>{d.items.map((x:any)=><tr key={x.id}><td>{x.product_name}</td><td>{fmt(x.sold_quantity)}</td><td>{fmt(x.remaining_quantity)}</td><td>{money(x.sales_amount,c)}</td><td>{x.remaining_policy}</td></tr>)}</tbody></table><section className="invoice-summary mt-6"><div><span>إجمالي المبيعات</span><strong>{money(s.total_sales_amount,c)}</strong></div><div><span>العمولة</span><strong>{money(s.commission_amount,c)}</strong></div><div className="invoice-total"><span>حصة المورد</span><strong>{money(s.supplier_share,c)}</strong></div>{c!=="SYP"&&<div><span>القيمة الأساسية</span><strong>{money(n(s.supplier_share)*n(s.exchange_rate),"SYP")}</strong></div>}</section></>}
