import { AlertCircle, ArrowRight, Boxes, History, LayoutDashboard, Plus, RefreshCw, SlidersHorizontal } from "lucide-react";
import { useCallback, useEffect, useState, type ReactNode } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { InventoryStatusBadge, StockBatchesTable } from "../../components/inventory";
import { Button, Card, EmptyState, LoadingSpinner } from "../../components/ui";
import { getInventoryErrorMessage, inventoryService, type InventoryItem, type StockAdjustment, type StockBatch } from "./inventoryService";

type Tab = "overview" | "batches" | "adjustments";
export default function ProductInventoryDetailsPage() {
  const { productId } = useParams(); const navigate = useNavigate(); const id = Number(productId);
  const [product, setProduct] = useState<InventoryItem>(); const [batches, setBatches] = useState<StockBatch[]>([]); const [adjustments, setAdjustments] = useState<StockAdjustment[]>([]);
  const [activeTab, setActiveTab] = useState<Tab>("overview"); const [isLoading, setIsLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { try { setIsLoading(true); setError(""); const details = await inventoryService.productDetails(id); setProduct(details.item); setBatches(details.batches); setAdjustments(details.adjustments); } catch (e) { setError(getInventoryErrorMessage(e)); } finally { setIsLoading(false); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  if (isLoading) return <div className="flex min-h-[60vh] items-center justify-center"><LoadingSpinner size="lg" /></div>;
  if (!product) return <EmptyState icon={<AlertCircle size={28} />} title="تعذر تحميل تفاصيل المخزون" description={error || "المادة غير موجودة."} action={<Button variant="secondary" startIcon={<RefreshCw size={16} />} onClick={() => void load()}>إعادة المحاولة</Button>} />;
  return <>
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><Button variant="secondary" startIcon={<ArrowRight size={17} />} onClick={() => navigate("/inventory")}>العودة إلى المخزون</Button><div className="flex flex-wrap gap-2"><Button variant="secondary" startIcon={<Plus size={17} />} onClick={() => navigate(`/inventory/${id}/batches/new`)}>إضافة دفعة</Button><Button startIcon={<SlidersHorizontal size={17} />} onClick={() => navigate(`/inventory/${id}/adjust`)}>تسوية المخزون</Button></div></div>
    <Card padding={false}>
      <div className="flex flex-col gap-5 border-b border-[var(--border)] p-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex flex-wrap items-center gap-3"><h1 className="text-2xl font-bold">{product.productName}</h1><InventoryStatusBadge status={product.status} /></div><div className="mt-2 flex flex-wrap gap-2 text-sm text-[var(--text-muted)]"><span dir="ltr">{product.productCode}</span><span>•</span><span>{product.categoryName}</span><span>•</span><span>{product.unit}</span></div></div><div className="grid min-w-full grid-cols-2 gap-3 sm:min-w-[420px] lg:min-w-[520px] lg:grid-cols-3"><Summary label="الرصيد الحالي" value={`${product.totalQuantity.toLocaleString()} ${product.unit}`} /><Summary label="قيمة المخزون" value={`${product.stockValue.toLocaleString()} ل.س`} /><Summary label="عدد الدفعات" value={batches.length.toLocaleString()} /></div></div>
      <div className="flex gap-1 overflow-x-auto border-b border-[var(--border)] px-5 pt-3"><TabButton active={activeTab === "overview"} icon={<LayoutDashboard size={16} />} onClick={() => setActiveTab("overview")}>نظرة عامة</TabButton><TabButton active={activeTab === "batches"} icon={<Boxes size={16} />} onClick={() => setActiveTab("batches")}>الدفعات ({batches.length})</TabButton><TabButton active={activeTab === "adjustments"} icon={<History size={16} />} onClick={() => setActiveTab("adjustments")}>التسويات ({adjustments.length})</TabButton></div>
      <div className="p-5">
        {activeTab === "overview" && <div className="grid gap-5 xl:grid-cols-2"><Card header="بيانات المخزون"><dl className="divide-y divide-[var(--border)]"><Line label="الرصيد الحالي" value={`${product.totalQuantity.toLocaleString()} ${product.unit}`} /><Line label="حد التنبيه المؤقت" value={`${product.minimumStock.toLocaleString()} ${product.unit}`} /><Line label="متوسط سعر الشراء" value={`${product.averagePurchasePrice.toLocaleString()} ل.س`} /><Line label="قيمة المخزون" value={`${product.stockValue.toLocaleString()} ل.س`} /><Line label="أقرب انتهاء" value={product.nearestExpiryDate ?? "لا يوجد"} /></dl></Card><Card header="التوريد والدفعات"><dl className="divide-y divide-[var(--border)]"><Line label="عدد الدفعات" value={batches.length.toLocaleString()} /><Line label="عدد الموردين" value={product.suppliersCount.toLocaleString()} /><div className="py-3"><dt className="text-xs text-[var(--text-muted)]">الموردون</dt><dd className="mt-2 flex flex-wrap gap-2">{product.supplierNames.length ? product.supplierNames.map((name) => <span key={name} className="rounded-full border border-[var(--border)] px-3 py-1 text-xs">{name}</span>) : <span className="text-sm text-[var(--text-muted)]">لا يوجد موردون</span>}</dd></div></dl></Card></div>}
        {activeTab === "batches" && (batches.length ? <div className="overflow-x-auto rounded-[var(--radius-md)] border border-[var(--border)]"><StockBatchesTable batches={batches} unit={product.unit} /></div> : <EmptyState title="لا توجد دفعات" description="أضف أول دفعة لهذه المادة." />)}
        {activeTab === "adjustments" && (adjustments.length ? <div className="overflow-x-auto rounded-[var(--radius-md)] border border-[var(--border)]"><table className="w-full text-sm"><thead className="bg-[var(--surface-subtle)]"><tr>{["التاريخ","الدفعة","العملية","الكمية","قبل","بعد","السبب"].map((x) => <th key={x} className="px-4 py-3 text-right">{x}</th>)}</tr></thead><tbody>{adjustments.map((a) => <tr key={a.id} className="border-t border-[var(--border)]"><td className="px-4 py-3" dir="ltr">{a.createdAt}</td><td className="px-4 py-3">#{a.stockBatchId}</td><td className="px-4 py-3">{a.quantity >= 0 ? "إضافة" : "خصم"}</td><td className="px-4 py-3" dir="ltr">{Math.abs(a.quantity).toLocaleString()} {product.unit}</td><td className="px-4 py-3">{a.quantityBefore.toLocaleString()}</td><td className="px-4 py-3">{a.quantityAfter.toLocaleString()}</td><td className="px-4 py-3">{a.reason}</td></tr>)}</tbody></table></div> : <EmptyState title="لا توجد تسويات" description="ستظهر هنا التسويات المنفذة على دفعات هذه المادة." />)}
      </div>
    </Card>
  </>;
}
function Summary({ label, value }: { label: string; value: string }) { return <div className="rounded-[var(--radius-sm)] bg-[var(--surface-subtle)] px-4 py-3"><p className="text-xs text-[var(--text-muted)]">{label}</p><p dir="ltr" className="mt-1 text-right font-bold">{value}</p></div>; }
function Line({ label, value }: { label: string; value: string }) { return <div className="grid grid-cols-[140px_1fr] gap-4 py-3"><dt className="text-sm text-[var(--text-muted)]">{label}</dt><dd className="text-sm font-bold">{value}</dd></div>; }
function TabButton({ active, icon, children, onClick }: { active: boolean; icon: ReactNode; children: ReactNode; onClick: () => void }) { return <button type="button" onClick={onClick} className={`flex items-center gap-2 border-b-2 px-4 py-3 text-sm font-bold ${active ? "border-[var(--primary)] text-[var(--primary)]" : "border-transparent text-[var(--text-muted)]"}`}>{icon}{children}</button>; }
