import type { ActivityLog } from "./activityLogsTypes";
export const activityLogsMock: ActivityLog[] = [
 { id: 1, userId: 1, userName: "مدير النظام", action: "cashbox.transfer", module: "الصناديق", entityType: "cashbox", entityId: 2, description: "تم تحويل مبلغ بين الصندوق الرئيسي وصندوق المبيعات.", severity: "critical", createdAt: "2026-08-03T10:25:00", oldData: { sourceBalance: 950000 }, newData: { sourceBalance: 700000 } },
 { id: 2, userId: 1, userName: "مدير النظام", action: "product.update", module: "المنتجات", entityType: "product", entityId: 14, description: "تم تعديل بيانات المنتج «سكر أبيض».", severity: "info", createdAt: "2026-08-03T09:42:00", oldData: { name: "سكر", code: "PRD-014" }, newData: { name: "سكر أبيض", code: "PRD-014" } },
 { id: 3, userId: 2, userName: "سارة أحمد", action: "stock.adjust", module: "المخزون", entityType: "stock_adjustment", entityId: 31, description: "تم تسجيل تسوية خصم بسبب تلف كمية من المخزون.", severity: "warning", createdAt: "2026-08-02T16:10:00", oldData: { quantity: 18 }, newData: { quantity: 15 } },
 { id: 4, userId: 1, userName: "مدير النظام", action: "supplier.create", module: "الموردون", entityType: "supplier", entityId: 9, description: "تمت إضافة مورد جديد «شركة الشرق».", severity: "info", createdAt: "2026-08-02T12:05:00", newData: { name: "شركة الشرق", phone: "0990000000", isActive: true } },
 { id: 5, userId: 3, userName: "محمد خالد", action: "transaction.delete", module: "المعاملات المالية", entityType: "financial_transaction", entityId: 48, description: "تم حذف سجل معاملة مالية تجريبية.", severity: "critical", createdAt: "2026-08-01T14:30:00", oldData: { type: "expense", amount: 45000, category: "نقل" } },
 { id: 6, userId: 2, userName: "سارة أحمد", action: "customer.update", module: "العملاء", entityType: "customer", entityId: 22, description: "تم تعديل رقم هاتف العميل.", severity: "info", createdAt: "2026-08-01T11:15:00", oldData: { phone: "0944000000" }, newData: { phone: "0944111111" } },
 { id: 7, userId: 1, userName: "مدير النظام", action: "settings.update", module: "الإعدادات", entityType: "setting", entityId: null, description: "تم تحديث معلومات الشركة المستخدمة في الطباعة.", severity: "warning", createdAt: "2026-07-31T18:20:00" },
];

