import { useEffect, useMemo, useState } from "react";
import { History } from "lucide-react";
import { useNavigate } from "react-router-dom";
import ActivityLogsToolbar from "../../components/activity-logs/ActivityLogsToolbar";
import ActivityLogsTable from "../../components/activity-logs/ActivityLogsTable";
import { Card, EmptyState, PageHeader, Pagination } from "../../components/ui";
import type { ActivityLog, ActivityLogFilters } from "./activityLogsTypes";
import { activityLogsService } from "./activityLogsService";
import { PATHS } from "../../routes/path";
const initialFilters:ActivityLogFilters={query:"",user:"all",module:"all",action:"all",severity:"all",dateFrom:"",dateTo:""};
export default function ActivityLogsPage(){ const navigate=useNavigate(); const [items,setItems]=useState<ActivityLog[]>([]); const [filters,setFilters]=useState(initialFilters); const [loading,setLoading]=useState(true); const [page,setPage]=useState(1); const pageSize=5; useEffect(()=>{activityLogsService.list().then(setItems).finally(()=>setLoading(false));},[]); const users=useMemo(()=>[...new Set(items.map(i=>i.userName))],[items]); const modules=useMemo(()=>[...new Set(items.map(i=>i.module))],[items]); const filtered=useMemo(()=>items.filter(item=>{const q=filters.query.trim().toLowerCase(); const date=item.createdAt.slice(0,10); return (!q||`${item.description} ${item.action} ${item.userName}`.toLowerCase().includes(q))&&(filters.user==="all"||item.userName===filters.user)&&(filters.module==="all"||item.module===filters.module)&&(filters.severity==="all"||item.severity===filters.severity)&&(!filters.dateFrom||date>=filters.dateFrom)&&(!filters.dateTo||date<=filters.dateTo);}),[items,filters]); const totalPages=Math.max(1,Math.ceil(filtered.length/pageSize)); const visible=filtered.slice((page-1)*pageSize,page*pageSize); function update(key:keyof ActivityLogFilters,value:string){setFilters(current=>({...current,[key]:value}));setPage(1);} return <><PageHeader title="سجل النشاط" description="واجهة تجريبية لعرض عمليات المستخدمين داخل النظام. البيانات الحالية وهمية إلى حين جاهزية الباك."/><Card padding={false} header="سجل العمليات" description="ابحث وفلتر السجلات ثم افتح التفاصيل لمقارنة البيانات قبل وبعد العملية."><ActivityLogsToolbar filters={filters} onChange={update} onClear={()=>{setFilters(initialFilters);setPage(1);}} users={users} modules={modules}/>{loading?<div className="p-10 text-center text-sm text-[var(--text-muted)]">جاري تحميل سجل النشاط...</div>:visible.length?<><ActivityLogsTable items={visible} onView={(item)=>navigate(PATHS.ACTIVITY_LOG_DETAILS.replace(":activityLogId",String(item.id)))}/><div className="px-5 pb-5"><Pagination page={Math.min(page,totalPages)} totalPages={totalPages} onChange={setPage}/></div></>:<EmptyState icon={<History size={34}/>} title="لا توجد سجلات مطابقة" description="غيّر الفلاتر أو امسح عبارة البحث لعرض السجلات."/>}</Card></>; }
