import { useMemo, useState } from "react";
import { Calculator, PackagePlus, Plus, Save, Trash2 } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import type { PaymentMethod, PurchaseDraft, PurchaseItem, PurchaseStatus, PurchaseType } from "../../components/purchases/types";
import { BackButton, Button, Card, FormField, FormSection, Input, PageHeader, Select, Textarea } from "../../components/ui";
import { PATHS } from "../../routes/path";
import { purchasesService } from "./purchasesService";

const emptyItem = (): PurchaseItem => ({ id: 0, productId: 0, productName: "", quantity: 1, purchasePrice: 0, lineTotal: 0, batchCode: "", receivedDate: new Date().toISOString().slice(0, 10), expiryDate: "" });
const money = (value: number) => value.toLocaleString("en-US");
export default function PurchaseFormPage() {
  const navigate = useNavigate();
  const { purchaseId } = useParams();
  const existing = purchaseId ? purchasesService.getById(Number(purchaseId)) : undefined;
  const lookups = purchasesService.getLookups();
  const [form, setForm] = useState<PurchaseDraft>({ invoiceNumber: existing?.invoiceNumber ?? "", supplierId: existing?.supplierId ?? 0, purchaseType: existing?.purchaseType ?? "standard", cashboxId: existing?.cashboxId ?? 1, invoiceDate: existing?.invoiceDate ?? new Date().toISOString().slice(0, 10), discount: existing?.discount ?? 0, tax: existing?.tax ?? 0, status: existing?.status ?? "draft", notes: existing?.notes ?? "", items: existing?.items ?? [emptyItem()], initialPayment: 0, paymentMethod: "cash", paymentReference: "" });
  const subtotal = useMemo(() => form.items.reduce((sum, item) => sum + item.quantity * item.purchasePrice, 0), [form.items]);
  const total = Math.max(0, subtotal - form.discount + form.tax);
  const remaining = Math.max(0, total - (existing?.paidAmount ?? 0) - form.initialPayment);
  const updateItem = (index: number, patch: Partial<PurchaseItem>) => setForm((current) => ({ ...current, items: current.items.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item) }));
  const selectProduct = (index: number, productId: number) => { const product = lookups.products.find((item) => item.id === productId); updateItem(index, { productId, productName: product?.name ?? "" }); };
  const submit = (status: PurchaseStatus) => {
    if (!form.supplierId || !form.items.length || form.items.some((item) => !item.productId || item.quantity <= 0 || item.purchasePrice < 0 || !item.batchCode)) return;
    const saved = purchasesService.save({ ...form, status }, existing?.id);
    navigate(`/purchases/${saved.id}`);
  };
  return <>
    <PageHeader title={existing ? `تعديل فاتورة ${existing.invoiceNumber}` : "فاتورة شراء جديدة"} description="أدخل بيانات المورد والأصناف ودفعات المخزون والمبالغ المالية." actions={<BackButton to={existing ? `/purchases/${existing.id}` : PATHS.PURCHASES} />} />
    <div className="space-y-5 pb-24">
      <FormSection title="بيانات الفاتورة" description="المورد ونوع الفاتورة والتاريخ والصندوق." icon={<PackagePlus size={18} />}>
        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><FormField label="رقم الفاتورة" htmlFor="invoiceNumber"><Input id="invoiceNumber" value={form.invoiceNumber} placeholder="يُنشأ تلقائيًا عند تركه فارغًا" onChange={(event) => setForm({ ...form, invoiceNumber: event.target.value })} /></FormField><FormField label="تاريخ الفاتورة" htmlFor="invoiceDate" required><Input id="invoiceDate" type="date" value={form.invoiceDate} onChange={(event) => setForm({ ...form, invoiceDate: event.target.value })} /></FormField><FormField label="المورد" htmlFor="supplier" required><Select id="supplier" value={String(form.supplierId)} options={[{ value: "0", label: "اختر المورد" }, ...lookups.suppliers.map((item) => ({ value: String(item.id), label: item.name }))]} onChange={(event) => setForm({ ...form, supplierId: Number(event.target.value) })} /></FormField><FormField label="نوع الفاتورة" htmlFor="purchaseType" required><Select id="purchaseType" value={form.purchaseType} options={[{ value: "standard", label: "فاتورة عادية" }, { value: "consignment", label: "فاتورة أمانة" }]} onChange={(event) => setForm({ ...form, purchaseType: event.target.value as PurchaseType })} /></FormField><FormField label="الصندوق" htmlFor="cashbox"><Select id="cashbox" value={String(form.cashboxId ?? 0)} options={lookups.cashboxes.map((item) => ({ value: String(item.id), label: item.name }))} onChange={(event) => setForm({ ...form, cashboxId: Number(event.target.value) })} /></FormField><FormField label="ملاحظات" htmlFor="notes" className="md:col-span-2 xl:col-span-3"><Textarea id="notes" value={form.notes ?? ""} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></FormField></div>
      </FormSection>
      <Card padding={false} header="أصناف الفاتورة" description="أضف المنتجات وحدد الكمية وسعر الشراء وبيانات دفعة المخزون.">
        <div className="space-y-4 p-4">{form.items.map((item, index) => <div key={`${item.id}-${index}`} className="rounded-[var(--radius-md)] border border-[var(--border)] bg-[var(--surface-subtle)] p-4"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><FormField label="المنتج" required><Select value={String(item.productId)} options={[{ value: "0", label: "اختر المنتج" }, ...lookups.products.map((product) => ({ value: String(product.id), label: product.name }))]} onChange={(event) => selectProduct(index, Number(event.target.value))} /></FormField><FormField label="الكمية" required><Input type="number" min="1" value={item.quantity} onChange={(event) => updateItem(index, { quantity: Number(event.target.value) })} /></FormField><FormField label="سعر الشراء" required><Input type="number" min="0" value={item.purchasePrice} onChange={(event) => updateItem(index, { purchasePrice: Number(event.target.value) })} /></FormField><FormField label="إجمالي السطر"><Input readOnly value={money(item.quantity * item.purchasePrice)} /></FormField><FormField label="كود الدفعة" required><Input value={item.batchCode} onChange={(event) => updateItem(index, { batchCode: event.target.value })} /></FormField><FormField label="تاريخ الاستلام" required><Input type="date" value={item.receivedDate} onChange={(event) => updateItem(index, { receivedDate: event.target.value })} /></FormField><FormField label="تاريخ الانتهاء"><Input type="date" value={item.expiryDate ?? ""} onChange={(event) => updateItem(index, { expiryDate: event.target.value })} /></FormField><div className="flex items-end"><Button variant="danger" startIcon={<Trash2 size={16} />} disabled={form.items.length === 1} onClick={() => setForm((current) => ({ ...current, items: current.items.filter((_, itemIndex) => itemIndex !== index) }))}>حذف الصنف</Button></div></div></div>)}</div>
        <div className="border-t border-[var(--border)] p-4"><Button variant="secondary" startIcon={<Plus size={17} />} onClick={() => setForm((current) => ({ ...current, items: [...current.items, emptyItem()] }))}>إضافة صنف</Button></div>
      </Card>
      <div className="grid gap-5 xl:grid-cols-[1fr_360px]">
        <FormSection title="الدفع الأولي" description="يمكن تسجيل دفعة مع إنشاء الفاتورة." icon={<Calculator size={18} />}><div className="grid gap-4 md:grid-cols-2"><FormField label="المبلغ المدفوع"><Input type="number" min="0" max={total} value={form.initialPayment} onChange={(event) => setForm({ ...form, initialPayment: Number(event.target.value) })} /></FormField><FormField label="طريقة الدفع"><Select value={form.paymentMethod} options={[{ value: "cash", label: "نقدي" }, { value: "bank", label: "تحويل بنكي" }, { value: "credit_card", label: "بطاقة" }, { value: "cheque", label: "شيك" }, { value: "online", label: "دفع إلكتروني" }]} onChange={(event) => setForm({ ...form, paymentMethod: event.target.value as PaymentMethod })} /></FormField><FormField label="رقم المرجع" className="md:col-span-2"><Input value={form.paymentReference ?? ""} onChange={(event) => setForm({ ...form, paymentReference: event.target.value })} /></FormField></div></FormSection>
        <Card header="ملخص الفاتورة" className="h-fit"><div className="space-y-3 text-sm">{[["المجموع الفرعي", subtotal], ["الخصم", -form.discount], ["الضريبة", form.tax], ["المدفوع", (existing?.paidAmount ?? 0) + form.initialPayment], ["المتبقي", remaining]].map(([label, value]) => <div key={String(label)} className="flex justify-between"><span className="text-[var(--text-muted)]">{label}</span><strong>{money(Number(value))}</strong></div>)}<div className="border-t border-[var(--border)] pt-3"><div className="flex justify-between text-base"><strong>الإجمالي النهائي</strong><strong className="text-[var(--primary)]">{money(total)}</strong></div></div></div><div className="mt-4 grid grid-cols-2 gap-3"><FormField label="الخصم"><Input type="number" min="0" value={form.discount} onChange={(event) => setForm({ ...form, discount: Number(event.target.value) })} /></FormField><FormField label="الضريبة"><Input type="number" min="0" value={form.tax} onChange={(event) => setForm({ ...form, tax: Number(event.target.value) })} /></FormField></div></Card>
      </div>
    </div>
    <div className="fixed bottom-0 left-0 right-[260px] z-20 border-t border-[var(--border)] bg-[var(--surface)]/95 px-6 py-3 backdrop-blur"><div className="flex justify-end gap-3"><Button variant="secondary" onClick={() => navigate(existing ? `/purchases/${existing.id}` : PATHS.PURCHASES)}>إلغاء</Button>{existing ? <Button startIcon={<Save size={17} />} onClick={() => submit(existing.status)}>حفظ التعديلات</Button> : <><Button variant="secondary" startIcon={<Save size={17} />} onClick={() => submit("draft")}>حفظ كمسودة</Button><Button startIcon={<Save size={17} />} onClick={() => submit("confirmed")}>حفظ وتأكيد</Button></>}</div></div>
  </>;
}
